# Generated by Django 2.0.9 on 2020-01-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chuangye', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cygsdetails',
            name='name',
            field=models.CharField(max_length=200, verbose_name='公司名'),
        ),
    ]
